function wp=d02_prepare_workpoint(trimConfig,P)
%D02_PREPARE_WORKPOINT One explicit immutable workpoint reused across cases.
% No derivative offset subtraction, physical retuning or hidden persistent cache.
% Tests may pass tighter numerical tolerances; the exact P is always retained.
t=tic;tr=run_trim_case(trimConfig,P);
if ~tr.success||~tr.physicalConverged
 error('d02:ProductionTrimRejected','Require accepted existing production trim.');
end
if abs(tr.config.gammaDeg)>1e-12||abs(tr.betaM)>1e-12
 error('d02:UnsupportedWorkpoint','Current service accepts level, fixed helicopter-mode points only.');
end
cmd=tr.uTrim([1 3 6]);L=tr.loads.components.rotorLeft;R=tr.loads.components.rotorRight;
zd=[tr.xTrim;L.inducedVelocity;R.inducedVelocity;cmd;0];zq=[tr.xTrim;cmd;0];
[fd,ed]=d02_rhs(zd,cmd,tr.betaM,P,'dynamic');[fq,eq]=d02_rhs(zq,cmd,tr.betaM,P,'quasisteady');
% Dimensional WORKPOINT limits, not external accuracy tolerances. Kept
% tighter than inherited D02 (0.05 body /0.005 inflow), not relaxed to pass.
report=struct('bodyDerivativeInf',norm(fd(1:9),inf),'inflowDerivativeInf',norm(fd(10:11),inf), ...
 'actuatorDerivativeInf',norm(fd(12:14),inf),'heightRateAbs',abs(fd(15)), ...
 'quasisteadyBodyDerivativeInf',norm(fq(1:9),inf), ...
 'sameStateForceDifference_N',norm(ed.FaeroProp-eq.FaeroProp), ...
 'sameStateMomentDifference_Nm',norm(ed.Mtotal-eq.Mtotal), ...
 'bodyLimit',1e-3,'inflowLimit',5e-3,'heightLimit',1e-8, ...
 'productionResidual',tr.report.residualNorm);
report.pass=ed.evaluationValid&&eq.evaluationValid&&report.bodyDerivativeInf<report.bodyLimit&& ...
 report.quasisteadyBodyDerivativeInf<report.bodyLimit&&report.inflowDerivativeInf<report.inflowLimit&& ...
 report.actuatorDerivativeInf<1e-12&&report.heightRateAbs<report.heightLimit;
if ~report.pass,error('d02:WorkpointRejected','Dynamic workpoint invalid: body %.3g inflow %.3g.',report.bodyDerivativeInf,report.inflowDerivativeInf);end
wp=struct('identity','D02_1_EXPLICIT_WORKPOINT','P',P,'trim',tr,'command',cmd, ...
 'dynamicState',zd,'quasisteadyState',zq,'report',report,'preparationSeconds',toc(t), ...
 'externalValidationReady',false,'physicsRole','GENERIC_BASELINE_NOT_XV15_IDENTITY');
end
